services:
  smartgroupbot:
    build: .
    container_name: smartgroupbot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=sqlite:///data/bot_database.db
      - BOT_NAME=${BOT_NAME:-SmartGroupBot}
      - BOT_PERSONALITY=${BOT_PERSONALITY:-Дружелюбный и умный помощник в групповых чатах}
      - RESPONSE_FREQUENCY=${RESPONSE_FREQUENCY:-2}
      - MIN_CONTEXT_MESSAGES=${MIN_CONTEXT_MESSAGES:-2}
      - MAX_CONTEXT_MESSAGES=${MAX_CONTEXT_MESSAGES:-10}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./smart_bot.log:/app/smart_bot.log
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/bot-info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 